language: cpp

jobs:
  include:
    - os: linux
      env: MAYA2GLTF_MAYA=2018 MAYA_LOCATION=Maya2glTF-dev-kits/Autodesk_Maya_2018_6_Update_DEVKIT_Linux/devkitBase/
    - os: linux
      env: MAYA2GLTF_MAYA=2019 MAYA_LOCATION=Maya2glTF-dev-kits/Autodesk_Maya_2019_2_Update_DEVKIT_Linux/devkitBase/
    - os: osx
      env: MAYA2GLTF_MAYA=2018 MAYA_LOCATION=Maya2glTF-dev-kits/Autodesk_Maya_2018_6_Update_DEVKIT_Mac/
    - os: osx
      env: MAYA2GLTF_MAYA=2019 MAYA_LOCATION=Maya2glTF-dev-kits/Autodesk_Maya_2019_2_Update_DEVKIT_Mac/

compiler:
  - clang

script:
  - git clone https://github.com/fire/Maya2glTF-dev-kits.git
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then MAYA_LOCATION+=$TRAVIS_BUILD_DIR cmake -B "build" -G "Unix Makefiles" -D MAYA_VERSION:string=$MAYA2GLTF_MAYA .; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd build && make; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then MAYA_LOCATION+=$TRAVIS_BUILD_DIR cmake -B "build" -G "Unix Makefiles" -D MAYA_VERSION:string=$MAYA2GLTF_MAYA .; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd build && make; fi
