language: cpp

os:
  - linux
  - osx

compiler:
  - clang

env:
  - MAYA2GLTF_MAYA=2018 MAYA2GLTF_DIR=Autodesk_Maya_2018_6_Update
  - MAYA2GLTF_MAYA=2019 MAYA2GLTF_DIR=Autodesk_Maya_2019_2_Update

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cmake; fi

script:
  - git clone https://github.com/fire/Maya2glTF-dev-kits.git
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then MAYA_LOCATION=Maya2glTF-dev-kits/`echo $MAYA2GLTF_DIR`_DEVKIT_Mac/ cmake -B "build" -G "Unix Makefiles" -D MAYA_VERSION:string=$MAYA2GLTF_MAYA .; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd build && make; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then MAYA_LOCATION=Maya2glTF-dev-kits/`echo $MAYA2GLTF_DIR`_DEVKIT_Linux/devkitBase/ cmake -B "build" -G "Unix Makefiles" -D MAYA_VERSION:string=$MAYA2GLTF_MAYA .; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd build && make; fi
